name: ci

on:
- push
- release

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Check out source code
        uses: actions/checkout@v1
      - name: generate lib/kube_deploy_tools/version.rb for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export VERSION=${GITHUB_REF##*/v}
          cat >lib/kube_deploy_tools/version.rb <<EOF
          module KubeDeployTools
            VERSION = '${VERSION}'
          end
          EOF
      - name: run unit tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake test
      - name: build gem
        run: bundle exec rake build
      - uses: toolmantim/release-drafter@v5.2.0
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push tagged gem to rubygems
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export VERSION=${GITHUB_REF##*/v}
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > $HOME/.gem/credentials
          chmod 600 $HOME/.gem/credentials
          gem push kube_deploy_tools-${VERSION}.gem
        env:
          GITHUB_TOKEN: ${{ secrets.RUBYGEMS_API_KEY }}
